# Generated by Django 2.1.7 on 2019-09-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20190904_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
