# Generated by Django 2.1.7 on 2019-09-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
