# Generated by Django 2.1.7 on 2019-09-06 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('orders', '0003_remove_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='payment.Payment'),
        ),
    ]
